# Устанавливаем Nginx
- name: Install Nginx
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

# Запускаем и включаем Nginx
- name: Start and enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

# Копируем конфигурационный файл Nginx (из шаблона)
- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

# Проверяем конфигурацию Nginx
- name: Check Nginx configuration
  command: nginx -t
  register: nginx_check
  changed_when: false

# Вывод результата проверки
- name: Display Nginx configuration check result
  debug:
    var: nginx_check.stdout
