# Устанавливаем Apache
- name: Install Apache
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

# Запускаем и включаем Apache
- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: yes

# Копируем конфигурационный файл Apache
- name: Deploy Apache configuration
  template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache

# Проверяем конфигурацию Apache
- name: Check Apache configuration
  command: apachectl configtest
  register: apache_check
  changed_when: false

# Вывод результата проверки
- name: Display Apache configuration check result
  debug:
    var: apache_check.stdout
