galaxy_info:
  role_name: nginx
  description: Установка и настройка веб-сервера Nginx
  author: Dmitry Rubanov
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
